#!/bin/node

/**
 * @file Checks If documentation data is up to date
 */

import crypto from "crypto"
import {dirname} from "path"
import {fileURLToPath} from "url"
import {promises as fs} from "fs"
import yaml from "yaml"
import getDocs from "./helpers/fetchDocs.mjs"

export const hash = (algo, contents, format = "hex") =>
    crypto.createHash(algo).update(contents).digest(format)

const __dirname = dirname(fileURLToPath(import.meta.url))

const newDocs = await getDocs()
const newDocsString = `# THIS IS AN AUTOGENERATED FILE; DO NOT EDIT DIRECTLY\n\n${yaml.stringify(
    newDocs,
    {
        sortMapEntries: true,
    },
)}`.trim()

const oldDocsString = (
    await fs.readFile(`${__dirname}/../data/documentation-data.yml`, "utf-8")
).trim()

if (hash("sha256", newDocsString) === hash("sha256", oldDocsString)) {
    console.log("Documentation data is up to date")
} else {
    throw new Error("Documentation is out of date")
}
